[program:taskbot]
directory=/home/telegrambot/projects/taskbot
command=/usr/bin/java -jar /home/telegrambot/projects/dazztutorbot/target/taskbot-1.0.0.jar
autostart=true
autorestart=true
startsecs=5
startretries=10
stderr_logfile=/home/telegrambot/projects/taskbot/logs/taskbot.err.log
stdout_logfile=/home/telegrambot/projects/taskbot/logs/taskbot.out.log
environment=BOT_USERNAME="protonchecklistbot",BOT_TOKEN="6543648927:AAH35YlUuoULg8GNqYPcIc1-LqidQqPDkKk",APP_TIMEZONE="Asia/Singapore",APP_MORNING_SUMMARY_TIME="08:00",APP_SCHEDULER_INTERVAL_SECONDS="60",APP_DB_PATH="/home/youruser/taskbot/data/taskbot.db",APP_DEFAULT_STALE_DAYS="3"
